### ISSUE TITLE
Fix Accidents Tab Issue

### ISSUE THREAD

**Issue by ngottlieb** [AmericanWhitewater/wh2o-vue#502]
Not clear what the problem is but accidents tab seems to be broken on prod:

```
TypeError: Cannot read properties of undefined (reading 'isBefore')
    at a.formatDate (app.700df321.js:446:4362)
    at chunk-2d0b1c28.d9ee20c0.js:1:2116
    at a.xe [as _l] (app.700df321.js:63:16032)
    at fn (chunk-2d0b1c28.d9ee20c0.js:1:2026)
    at Object.r [as main] (app.700df321.js:63:15647)
    at a.xe [as _l] (app.700df321.js:63:16335)
    at a.<anonymous> (app.700df321.js:73:31859)
    at t._render (app.700df321.js:63:35409)
    at a.r (app.700df321.js:63:64876)
    at fn.get (app.700df321.js:63:26750)
```

**Comment by AWKevin** [comment]
Nice.
